### ISSUE TITLE
Preconfigure daemons

### ISSUE THREAD

**Issue by chapterjason** [SoureCode/DaemonBundle#3]
Add a preconfiguration for ids.

Basically something like that:

```yaml
soure_code_daemon_bundle:
    daemons:
        npm: npm run watch
```

And then it should be enough to run just: `symfony console daemon:start --id npm`.

The process argument becomes optional.
Add a check if there is a preconfigured daemon, if not, the process argument becomes mandatory.
